//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MESFeedClientEFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblServiceBusIntakeDtl
    {
        public int Id { get; set; }
        public string MessageId { get; set; }
        public string AHAssetID { get; set; }
        public string AHAssetDesc { get; set; }
        public string AHAssetStatus { get; set; }
        public string AHStateName { get; set; }
        public Nullable<System.DateTime> AHLastModified { get; set; }
        public string AHScopeName { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateAction { get; set; }
    }
}
