//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MESFeedClientEFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblServiceBusDtlSchedule
    {
        public int Id { get; set; }
        public string MessageId { get; set; }
        public Nullable<int> SchedRowID { get; set; }
        public string M_AEScheduleType { get; set; }
        public string M_EVRTName { get; set; }
        public string M_EHEVID { get; set; }
        public Nullable<System.DateTime> AEDueDate { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
