//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MESFeedClientEFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkOrderFeedLog
    {
        public int Id { get; set; }
        public string TransactionID { get; set; }
        public System.DateTimeOffset TransactionDate { get; set; }
        public string TransactionType { get; set; }
        public string MfgOrderName { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
        public string OrderStatus { get; set; }
        public string OrderType { get; set; }
        public string Factory { get; set; }
        public string ProductName { get; set; }
        public string ProductRevision { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string UOM { get; set; }
        public string Priority { get; set; }
        public Nullable<System.DateTimeOffset> ReleaseDate { get; set; }
        public string CompletionSubInventory { get; set; }
        public Nullable<System.DateTimeOffset> PlannedStartDate { get; set; }
        public Nullable<System.DateTimeOffset> PlannedCompletionDate { get; set; }
        public string LotNumber { get; set; }
        public string MaterialProductName { get; set; }
        public string MaterialProductRevision { get; set; }
        public Nullable<int> IssueControl { get; set; }
        public string DefaultStockPullLocation { get; set; }
        public string ErpOperation { get; set; }
        public Nullable<int> QuantityRequired { get; set; }
        public Nullable<bool> AllowSubstitution { get; set; }
        public Nullable<bool> AllowUnderConsumption { get; set; }
        public Nullable<bool> AllowOverConsumption { get; set; }
        public string AttributeName { get; set; }
        public string AttributeDataType { get; set; }
        public string AttributeValue { get; set; }
        public string AttributeIsExpression { get; set; }
        public string Action { get; set; }
        public string XmlRequest { get; set; }
        public string XmlResponse { get; set; }
    }
}
