CREATE TABLE [dbo].[tblWorkOrderFeedLog]
(
	[Id] INT Identity(1,1) NOT NULL PRIMARY KEY,
	[TransactionID] nvarchar(250) not null,
	[TransactionDate] datetimeoffset not null,
	[TransactionType] nvarchar(50) not null,
	[MfgOrderName] nvarchar(20) null,
	[Description] nvarchar(150) null,
	[Notes] nvarchar(350) null,
	[OrderStatus] nvarchar(20) null,
	[OrderType] nvarchar(20) null,
	[Factory] nvarchar(50) null,
	[ProductName] nvarchar(150) null,
	[ProducntRevision] nvarchar(50) null,
	[Quantity] int null,
	[UOM] nvarchar(10) null,
	[Priority] nvarchar(50) null,
	[ReleaseDate] datetimeoffset null, 
	[CompletionSubInventory] nvarchar(30) null,
	[PlannedStartDate] datetimeoffset null,
	[PlannedCompletionDate] datetimeoffset null,
	[LotNumber] nvarchar(20) null,
	[MaterialProductName] nvarchar(150) null,
	[MaterialProductRevision] nvarchar(50) null,
	[IssueControl] int null,
	[DefaultStockPullLocation] nvarchar(100) null,
	[ErpOperation] nvarchar(50) null,
	[QuantityRequired] int null,
	[AllowSubstitution] bit null,
	[AllowUnderConsumption] bit null,
	[AllowOverConsumption] bit null,
	[AttributeName] nvarchar(50),
	[AttributeDataType] nvarchar(50),
	[AttributeValue] nvarchar(50),
	[AttributeIsExpression] nvarchar(50),
	[Action] nvarchar(100) null,
	[XmlRequest] nvarchar(max) null,
	[XmlResponse] nvarchar(max) null
)
