//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDBModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeOrderRequiredTraining
    {
        public int ChangeOrderRequiredTrainingId { get; set; }
        public string ChangeOrderNumber { get; set; }
        public string EmployeeNumber { get; set; }
        public string EmployeeName { get; set; }
        public string DocumentId { get; set; }
        public string Revision { get; set; }
        public string RequiredTrainingLevel { get; set; }
        public Nullable<int> DueDateModifier { get; set; }
        public bool Active { get; set; }
        public bool Committed { get; set; }
        public System.DateTime CreatedAtDateTime { get; set; }
        public string CreatedByUser { get; set; }
        public Nullable<System.DateTime> ModifiedAtDateTime { get; set; }
        public string ModifiedByUser { get; set; }
        public Nullable<int> ModifiedReasonCode { get; set; }
        public string ModifiedReasonOther { get; set; }
        public Nullable<System.DateTime> InactivatedAtDateTime { get; set; }
        public string InactivatedByUser { get; set; }
        public Nullable<int> InactivatedReasonCode { get; set; }
        public string InactivatedReasonOther { get; set; }
    }
}
