//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDBModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElectronicSignature
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ElectronicSignature()
        {
            this.tblCurrentTrainingRequirements = new HashSet<tblCurrentTrainingRequirement>();
            this.tblCurrentTrainingRequirements1 = new HashSet<tblCurrentTrainingRequirement>();
            this.tblTrainingHistories = new HashSet<tblTrainingHistory>();
            this.tblTrainingHistories1 = new HashSet<tblTrainingHistory>();
        }
    
        public System.Guid ElectronicSignatureId { get; set; }
        public string UserName { get; set; }
        public string EmployeeNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime PasswordVerifiedDateTime { get; set; }
        public Nullable<System.DateTime> ExecutedDateTime { get; set; }
        public string ExecutedPurpose { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCurrentTrainingRequirement> tblCurrentTrainingRequirements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCurrentTrainingRequirement> tblCurrentTrainingRequirements1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTrainingHistory> tblTrainingHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTrainingHistory> tblTrainingHistories1 { get; set; }
    }
}
