//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDBModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCurrentTrainingRequirement
    {
        public int CurrentTrainingID { get; set; }
        public string Employee_number { get; set; }
        public string CurrentTrainingDocID { get; set; }
        public Nullable<System.DateTime> EnteredDate { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.Guid> AssignedByElectronicSignatureId { get; set; }
        public string CurrentTrainingType { get; set; }
        public string Previous_Employee_Number { get; set; }
        public Nullable<System.DateTime> Employee_Number_UpdatedOn { get; set; }
        public string Employee_Number_UpdatedBy { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.Guid> DeletedByElectronicSignatureId { get; set; }
    
        public virtual ElectronicSignature ElectronicSignature { get; set; }
        public virtual ElectronicSignature ElectronicSignature1 { get; set; }
    }
}
