//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDBModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTrainingHistory
    {
        public int TrainingHistoryID { get; set; }
        public string Employee_Number { get; set; }
        public string TrainTitle { get; set; }
        public string TrainDeptName { get; set; }
        public string TrainDeptNum { get; set; }
        public string TrainDocID { get; set; }
        public string TrainDocRev { get; set; }
        public string TrainValidatedByNumber { get; set; }
        public string TrainValidatedByFirstName { get; set; }
        public string TrainValidatedByLastName { get; set; }
        public Nullable<System.DateTime> TrainDate { get; set; }
        public Nullable<System.DateTime> EnteredDate { get; set; }
        public string EnteredBy { get; set; }
        public string Previous_Employee_Number { get; set; }
        public Nullable<System.DateTime> Employee_Number_UpdatedOn { get; set; }
        public string Employee_Number_UpdatedBy { get; set; }
        public Nullable<System.Guid> ElectronicSignatureId { get; set; }
        public string TrainingLevel { get; set; }
        public string ActiveTrainingApproval { get; set; }
        public string ActiveTrainingApprovedBy { get; set; }
        public Nullable<System.DateTime> ActiveTrainingApprovedOn { get; set; }
        public Nullable<System.Guid> ActiveTrainingElecronicSignatureId { get; set; }
    
        public virtual ElectronicSignature ElectronicSignature { get; set; }
        public virtual ElectronicSignature ElectronicSignature1 { get; set; }
    }
}
