//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDBModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class xxatr_jobprocedure_tracking
    {
        public int trackID { get; set; }
        public string employee_number { get; set; }
        public string job_number { get; set; }
        public string job_type { get; set; }
        public Nullable<System.Guid> scanID { get; set; }
        public string bundle { get; set; }
        public string doc_ID { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<bool> isTraining { get; set; }
        public string recordedBy { get; set; }
        public Nullable<System.DateTime> logoutDate { get; set; }
        public string trainerEmployeeId { get; set; }
    }
}
